let shopItemsData = [
    {
      id: "Produkt1",
      name: "Nóż Santoku Ki no Ha",
      price: 45,
      desc: "Kompaktowy nóż Santoku z eleganckim drewnianym uchwytem. Idealny do krojenia mięsa, warzyw i owoców, inspirowany japońską sztuką nożownictwa.",
      img: "produkty/p1.jpg",
      category: "Noże",
    },
    {
      id: "Produkt2",
      name: "Nóż Gyuto Shokunin",
      price: 100,
      desc: "Wszechstronny nóż kuchenny Gyuto o ostrzu z najwyższej jakości stali nierdzewnej. Stworzony dla szefów kuchni i domowych pasjonatów.",
      img: "produkty/p2.jpg",
      category: "Noże",
    },
    {
      id: "Produkt3",
      name: "Nóż Santoku Kaze",
      price: 300,
      desc: "Nóż Santoku z ergonomicznym uchwytem i ostrzem o wyjątkowej ostrości. Perfekcyjny do precyzyjnego siekania i krojenia.",
      img: "produkty/p3.jpg",
      category: "Noże",
    },
    {
        id: "Produkt4",
        name: "Nóż uniwersalny do filetowania",
        price: 45,
        desc: "Lekki i precyzyjny nóż do filetowania z japońskim ostrzem. Doskonały do ryb, mięsa i innych delikatnych produktów.",
        img: "produkty/4.jpeg",
        category: "Noże",
    },
    {
        id: "Produkt5",
        name: "Nóż kuchenny japoński (uchwyt z drewna)",
        price: 100,
        desc: "Tradycyjny japoński nóż kuchenny z ręcznie wykonanym uchwytem z naturalnego drewna. Idealny do codziennej pracy w kuchni.",
        img: "produkty/5.jpeg",
        category: "Noże",
    },
    {
        id: "Produkt6",
        name: "Garnek żeliwny z pokrywką IronPro",
        price: 300,
        desc: "Ekskluzywny zestaw noży z czarnym wykończeniem. Doskonałe narzędzia dla profesjonalistów i miłośników gotowania.",
        img: "produkty/6.jpeg",
        category: "Garnki",
    },
    {
        id: "Produkt7",
        name: "Garnek emaliowany Scarlet",
        price: 45,
        desc: "Stylowy garnek emaliowany w głębokiej czerwieni. Idealny do gotowania i serwowania – łączy elegancję z funkcjonalnością.",
        img: "produkty/7.jpeg",
        category: "Garnki",
      },
      {
        id: "Produkt8",
        name: "Talerz obiadowy Indigo Wave",
        price: 100,
        desc: "Ręcznie wykonany talerz o unikalnym wzorze inspirowanym oceanicznymi falami. Doskonały na specjalne okazje.",
        img: "produkty/8.jpeg",
        category: "Talerze",
      },
      {
        id: "Produkt9",
        name: "Miska ceramiczna Midnight Black",
        price: 300,
        desc: "Elegancka, czarna miska ceramiczna. Idealna do serwowania zup, sałatek i deserów – klasyka w nowoczesnym wydaniu.",
        img: "produkty/9.jpeg",
        category: "Miski",
      },
      {
        id: "Produkt10",
        name: "Zestaw sztućców japońskich Ebony Cutlery",
        price: 45,
        desc: "Ręcznie wykonany zestaw sztućców z ciemnymi, drewnianymi uchwytami. Perfekcyjne połączenie stylu i jakości.",
        img: "produkty/10.jpg",
        category: "Sztućce",
      },
      {
        id: "Produkt11",
        name: "Zestaw noży szefa kuchni GrandMaster",
        price: 100,
        desc: "Wyjątkowy zestaw noży z najwyższej jakości stali damasceńskiej. Idealny do precyzyjnego krojenia i siekania, inspirowany japońską sztuką nożownictwa.",
        img: "produkty/11.jpeg",
        category: "Zestawy",
      },
      {
        id: "Produkt12",
        name: "Łyżka kuchenna Elegance Black",
        price: 300,
        desc: "Stylowa i odporna na temperatury łyżka o nowoczesnym designie. Doskonała do serwowania i codziennego gotowania.",
        img: "produkty/12.png",
        category: "Przybory kuchenne",
      },
      {
        id: "Produkt13",
        name: "Szpatuła GrillMaster Pro",
        price: 45,
        desc: "Solidna szpatuła z drewnianą rączką. Niezastąpiona do obracania steków, burgerów i warzyw na grillu – trwała i funkcjonalna.",
        img: "produkty/13.webp",
        category: "Przybory kuchenne",
      },
      {
        id: "Produkt14",
        name: "Wok Hammered Steel Pro",
        price: 100,
        desc: "Ręcznie młotkowany wok z żelaza. Doskonały do szybkich dań stir-fry, rozprowadza ciepło równomiernie dla perfekcyjnych rezultatów.",
        img: "produkty/14.webp",
        category: "Patelnie",
      },
      {
        id: "Produkt15",
        name: "Patelnia grillowa GrillMax Steel",
        price: 300,
        desc: "Żeliwna patelnia grillowa z żebrowaną powierzchnią, która nadaje potrawom wyjątkowy smak grilla. Ergonomiczny uchwyt z drewna zapewnia wygodę.",
        img: "produkty/15.jpg",
        category: "Patelnie",
      },
  ];